name: flutter_demo_it415_firebase
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  cloud_firestore: ^5.4.2
  hooks_riverpod: ^2.5.4
  freezed_annotation: ^2.4.4
  envied: ^0.5.4+1
  file_picker: ^8.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.8
  build_runner: ^2.4.13
  husky: ^0.1.7
  dartz: ^0.10.1
  test: ^1.25.7
  freezed: ^2.5.7
  envied_generator: ^0.5.4+1

# dart run build_runner build
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - secret.env 
